name = 'Uwezo Hugo'
license = 'MIT'
licenselink = 'https://github.com/avicndugu/uwezo-hugo/LICENSE'
description = 'This is a simple Hugo blog theme'

homepage = 'https://github.com/avicndugu/uwezo-hugo/'

demosite = 'https://uwezo-hugo-site.pages.dev/'

tags = ['blog', 'personal', 'light', 'hugo-theme','hugo-template']
features = ['responsive', 'simple', 'minimalistic']

[author]
  name = 'Avic Ndugu'
  homepage = 'https://dev.avicndugu.com'
